config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  # Deleted extra routes automatically generated by Rails
  devise_for :users
  root to: 'pages#home'
  get 'dashboard', to: 'pages#dashboard'
  resources :users, only: [:show] do
    resources :reviews, only: [:index, :new, :create]
  end
  resources :events do
    resources :requests, only: [:new, :create, :edit, :update]
  end
  # According to Alexander, destroy action of requests should not be nested into events
  resources :requests, only: :destroy do
    member do
      get "confirmation"
      # root for the request confirmation page
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  CATEGORIES = ["Poverty", "Women & Families", "Refugees", "Children", "Animals", "Environment", "Elderly", "Education"]
  belongs_to :user
  has_many :requests
  has_many :users, through: :requests
  has_one_attached :photo
  validates :photo, attached: true
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  def starts_at_formatted
    starts_at.strftime('%a, %d %b %k:%M ')
  end

  def ends_at_formatted
    ends_at.strftime('%a, %d %b %k:%M')
  end

  def ends_at_time
    ends_at.strftime('%k:%M')
  end
end

app/models/request.rb
class Request < ApplicationRecord
  enum status: [:pending, :confirmed, :declined, :cancelled ]
  # validates :status, inclusion: {in: [0,1,2,3]}
  belongs_to :user
  belongs_to :event
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :reviewer, class_name: "User"
  belongs_to :reviewee, class_name: "User"
  validates :rating, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:Charity, :Volunteer]
  has_many :requests, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :reviews_as_reviewer, class_name: "Review", foreign_key: :reviewer_id, dependent: :destroy
  has_many :reviews_as_reviewee, class_name: "Review", foreign_key: :reviewee_id, dependent: :destroy
  has_one_attached :photo
  validates :photo, attached: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
  def reset_notifications
    current_user.notifications = 0
  end
  def default_url_options
    { host: ENV["DOMAIN"] || "localhost:3000" }
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.geocoded

    if params[:search].present?
      sql = "name ILIKE :query
      OR category ILIKE :query
      OR address ILIKE :query
      OR description ILIKE :query
      "
      @events = Event.where(sql, query: "%#{params[:search][:query]}%").geocoded
      @events = @events.where(category: params[:search][:category]).geocoded if params[:search][:category].present?
    end

    @events_today = @events.select do |event|
      event.starts_at >= Date.today
    end

    @markers = @events.map do |event|
      if event.starts_at > Date.today
      {
        lat: event.latitude,
        lng: event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: event }),
        image_url: helpers.asset_url('world.png'),
        id: event.id
      }
      end
    end
    @markers.compact!
  end

  def show
    event = Event.geocoded
    @markers = [{
        lat: @event.latitude,
        lng: @event.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { event: @event }),
        image_url: helpers.asset_url('world.png')
      }]
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new(event_params)
    @event.user = current_user
      if @event.save
        redirect_to dashboard_path
      else
        render :new
      end
  end

  def edit
  end

  def update
    @event.update(event_params)
    if @event.save
     redirect_to event_path(@event)
    else
      render :edit
    end
  end

  def destroy
    @event.destroy
    redirect_to events_path
  end

  # def filter
  #     @future_events = @events.select do |event|
  #     event.starts_at > Date.today
  #   end
  # end

  private

  def event_params
    params.require(:event).permit(:name, :address, :description, :category, :starts_at, :ends_at, :capacity, :photo)
  end

  def set_event
    @event = Event.find(params[:id])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.select do |event|
      event.starts_at >= Date.today
    end
  end

  def dashboard
    if @user = current_user
      if @user.role == "Volunteer"
        @future_requests = @user.requests.select do |request|
          request.event.starts_at > Date.today
        end
        @past_requests = @user.requests.select do |request|
          request.event.starts_at < Date.today
        end
      elsif @user.role == "Charity"
        @events = @user.events
      end
    end
  end
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:new, :create, :edit, :update]

  def new
    @request = Request.new
  end

  def create
    @request = Request.new(request_params)
    @request.event = @event
    @request.user = current_user
    @request.status = 0
    if @request.save!
       redirect_to confirmation_request_path(@request)
     else
      render :new
    end
  end

  def edit
    @request = Request.find(params[:id])
  end

  def update

    @request = Request.find(params[:id])
    @request.status = params[:request][:status].to_i
    @request.update!(request_params)
    user_update
    redirect_to event_path(@event)
    #added for the user notification
  end


  def destroy
    @request = Request.find(params[:id])
    @request.destroy
    redirect_to root_path
    # need to be change when dashboard is available
  end

  def confirmation
  end

  def user_update
    other_user = @request.user
    other_user.notifications += 1
    other_user.save

  end


  private

  def request_params
    params.require(:request).permit(:message)
  end
  def set_event
    @event = Event.find(params[:event_id])

  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_user

  def index
  end

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.reviewer = current_user
    @review.reviewee = User.find(params[:user_id])
    if @review.save
      redirect_to user_path(@user)
    else
      render :new
    end
  end

  private

  def set_user
    @user = User.find(params[:user_id])
  end

  def review_params
    params.require(:review).permit(:rating, :message)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, only: [:show]
  def index
    @users = User.all
  end

  def show
  end

  private

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/views/events/_form.html.erb
<%= simple_form_for [@event] do |f| %>
<%= f.input :name %>
<%= f.input :category, collection: Event::CATEGORIES %>
<%= f.input :description %>
<%= f.input :address %>
<%= f.input :starts_at, order: [:day, :month, :year] %>
<%= f.input :ends_at, order: [:day, :month, :year] %>
<%= f.input :photo, as: :file %>
<%= f.input :capacity %>
<%= f.submit "Submit", class: "button-chip-main" %>
<% end %>

app/views/events/_info_window.html.erb
<div class="info-window">
  <%= cl_image_tag event.photo.key, width: 100 %>
  <h4><%= link_to(event.name, event_path(event)) %></h4>
  <p><%= event.starts_at_formatted %> to <%= event.ends_at_time %></p>
</div>

app/views/events/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>hello</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>

app/views/events/edit.html.erb
<div class="container">

  <h2>Edit your Event:</h2>
    <%= render 'form' %>
    <%= link_to 'See all events', events_path, class: "button-chip-main" %>

</div>

app/views/events/index.html.erb
<div class="d-flex">
  <div class="container" id="indexcontainer">

      <%= simple_form_for :search, url: events_path, method: "GET" do |f| %>
        <div class="d-flex justify-content-center align-items-center form-inline" id="category-form">
          <% if params[:search].present? %>
            <%= f.input :category, label: "Cause", collection: Event::CATEGORIES, prompt: "#{params[:search][:category]}"%>
          <% else %>
          <%= f.input :category, label: "Cause", collection: Event::CATEGORIES %>
          <% end %>
            <%= f.hidden_field :query, value: "#{params[:search][:query]}" if params[:search].present? %>
            <%= f.submit "Search", class: "button-chip-main" %>
        </div>
    <div class="row">
      <% @events.each do |event| %>
      <% if event.starts_at > Date.today %>
      <div class="m-4 col-xl-5 col-lg-11 col-md-6 col-sm-12 p-0 text-center">
        <div class="card-chip">
          <div class="event-content d-flex flex-column">
            <%= link_to event_path(event) do %>
              <div class="card-chip-image mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.2)),url(<%= cl_image_path event.photo.key %>)">
                <div class="card-chip-spots">
                  <p class="mb-0 p-1 text-center"><div class="spots-left-card d-flex align-items-center"><div class="spots-left-circle d-flex align-items-center justify-content-center text-dark m-2"><%= event.capacity - event.requests.length %></div> spots left</div></p>
                </div>
              </div>
            <% end %>
            <div class="pl-3 pb-3 pr-3 d-flex flex-column">
              <div class="card-chip-title text-center">
                <h3 class="mb-0"><%= link_to(event.name, event_path(event), class: "event-link") %></h3>
              </div>
              <div class="d-flex flex-column justify-content-between">
                <div class="card-chip-description">
                  <p class="color-secondary"><i class="fas fa-calendar-times mr-3"></i>   <%= event.starts_at_formatted%> to <%= event.ends_at_time %></p>
                  <a class="user-link" href="#" data-toggle="modal" data-target="#modal-<%= event.user.id %>">
                  <p><i class="fas fa-user-friends mr-3"></i><i class="fas fa-caret-right"></i> <strong class="in-card-link"><%= event.user.username %></strong></p>
                  </a>
                </div>
                  <div class="modal fade" id="modal-<%=event.user.id%>" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                    <div class="modal-dialog modal-lg" role="document">
                      <div class="modal-content">
                        <div class="modal-header">
                          <h5 class="modal-title" id="exampleModalLabel"><%= event.user.username%>'s profile</h5>
                          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                        <div class="modal-body">
                          <p>Contact person: <%=event.user.full_name %></p>
                          <div class="d-flex justify-content-around p-3">
                            <%= cl_image_tag(event.user.photo.key, id: "modal-photo", class: "mb-3") %>
                            <p class="p-3"><%= event.user.bio %></p>
                          </div>
                          <div class="d-flex">
                            <div>
                              <p><i class="fas fa-globe mr-3"></i><i class="fas fa-caret-right"></i><%= link_to " #{event.user.username}'s Website", event.user.webpage , target: "_blank", rel: "nofollow", class: "user-link ml-1"  %></p>
                                <ul class="no-bullet-points mt-5">
                                  <% event.user.events.each do |event|%>
                                    <% if event.starts_at > Date.today %>
                                      <li><i class="fas fa-calendar-times mr-3"></i><i class="fas fa-caret-right ml-1" style="color:#856c8b"></i> <%= link_to(event.name, event_path(event), class: "event-link ml-1", target: "_blank") %><p class="ml-5"><%= event.starts_at_formatted %> to <%= event.ends_at_time %></p></li>
                                    <% end %>
                                  <% end %>
                                </ul>
                                </div>
                            <p><i class="fas fa-user-friends ml-5 mr-3"></i><i class="fas fa-caret-right"></i><%= link_to " View full profile", user_path(event.user), class: "user-link ml-1" %></p>
                          </div>
                        </div>
                        <div class="modal-reviews">
                          <h5 class="m-3">Reviews:</h5>
                          <% event.user.reviews_as_reviewee.each do |review| %>
                            <div class="review ml-3">
                              <% review.rating.times do %>
                                <i class="fas fa-star" style="color: #EDB867"></i>
                              <% end %>
                              <% (5 - review.rating).times do %>
                                <i class="far fa-star" style="color: #EDB867"></i>
                              <% end %>
                              <p><em>"<%= review.message %>"</em></p>
                            </div>
                          <% end %>
                        </div>
                        <div class="modal-footer">
                          <button type="button" class="button-chip-secondary" data-dismiss="modal">Close</button>
                        </div>
                      </div>
                    </div>
                  </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
    </div>
     <% end %>

    <% if @events_today.length == 0 %>
         <div class="error">
          <p>Sorry, no results found</p>
          <%= link_to("Try Again", root_path, class: "button-chip-secondary") %></p>
        </div>
    <% end %>
  </div>
  <div id="map" class="w-50"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>

</div>

app/views/events/new.html.erb
<div class="container">
  <h2>Add an Event:</h2>
    <%= render 'form' %>
    <%= link_to 'See all events', events_path, class: "button-chip-main" %>
</div>

app/views/events/show.html.erb
<div class="container" id="show-page-content">
  <div class="content-show d-flex flex-column">
    <div class="border-bottom d-flex align-items-center justify-content-between p-4">
      <div class="d-flex align-items-center justify-content-between">
        <div class="charity-wrapper mr-2">
          <%= cl_image_tag @event.user.photo.key, width: "70px", class: "w-100" %>
        </div>
        <h5 class="m-0 p-0"><%= link_to(@event.user.username, user_path(@event.user), class: "user-link") %></h5>
      </div>
      <div class="m-0 p-0 d-flex align-items-center">
        <div class="spots-left-circle color-secondary d-flex align-items-center justify-content-center">
          <strong><%= @event.capacity - @event.requests.length %></strong>
        </div>
        <div class="color-secondary">spots left!</div>
      </div>
    </div>
    <div class="row">
      <div class="image-container col-lg-4 col-sm-12">
          <%= cl_image_tag @event.photo.key, width: "300px" %>
      </div>
      <div class="col-lg-8 col-sm-12 py-8">
        <div class="p-4">
          <h3 class="mb-3"><%= @event.name %></h3>
          <p class="color-tertiary"><%= @event.description %></p>
          <div class="d-flex align-items-center justify-content-start mb-3">
            <i class="fas fa-map-marker-alt mr-2"></i>
            <p class="m-0"><%= @event.address %></p>
          </div>
          <% if @event.requests.present? %>
            <div class="d-flex align-items-center justify-content-start mb-3">
              <% @event.requests.sample(2).each do |request|%>
                <%= cl_image_tag request.user.photo.key, class: "avatar", id: "avatar-participant", title: request.user.username%>
              <% end %>
              <% if @event.requests.length > 2 %>
                <div class="ml-2">
                  <p class="color-tertiary m-0"> + <%= @event.requests.length - 2 %> more </p>
                </div>
              <% end %>
            </div>
          <% end %>
          <p><strong>From:</strong> <%= @event.starts_at_formatted %></p>
          <p><strong>To:</strong> <%= @event.ends_at_formatted %></p>
          <%= link_to "Participate", new_event_request_path(@event), class: 'button-chip-main' %>
        </div>
      </div>
    </div>
  </div>

  <div
  id="map"
  style="width: 100%;
  height: 400px;"
  data-markers="<%= @markers.to_json %>"
  data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
  ></div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= meta_title %></title>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- <title>Chip In</title> -->
  <link rel="icon" type="image/png" href="https://res.cloudinary.com/dqlvehu5z/image/upload/v1583424588/CHIP-IN/Charities%20pics/world_cjvsmh.png" />
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_pack_tag 'application', media: 'all' %>
</head>
<body>
  <div class="content">
    <% if (params[:controller] == 'pages' && params[:action] == "dashboard")  %>
      <% current_user.notifications = 0%>
      <% current_user.save %>
    <% end %>
    <%= render "shared/navbar" %>
   <%= render "shared/flashes" %>
    <%= yield %>
    <div class="push"></div>
  </div>
    <%= render "shared/footer" %>

  <%= javascript_include_tag 'application' %>
  <%= javascript_pack_tag 'application' %>
</body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <% if @user.role == "Volunteer"%>
  <div class="future-events">
    <section class="section">
      <div class="container py-4">
        <ul class="nav nav-pills mb-3 justify-content-center" id="pills-tab" role="tablist">
          <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true"><h3>Upcoming Events</h3></a>
          </li>
          <li class="nav-item dashboard-options">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false"><h3>Past Events</h3></a>
          </li>
        </ul>
        <hr>
        <div class="tab-content" id="pills-tabContent">
          <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <div class="container py-1">
              <div class="row h-100 justify-content-center">
                <% if @future_requests.length > 0 %>
                <% @future_requests.each do |request| %>
                <% event = request.event %>
                <div class="col-lg-4 col-sm-12 p-0 m-4">
                  <div class="card-chip">
                    <div class="event-content d-flex flex-column">
                        <div class="card-chip-image mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.2)),url(<%= cl_image_path event.photo.key %>)">
                        </div>
                        <div class="pl-3 pb-3 pr-3 d-flex flex-column">
                            <div class="card-chip-title text-center">
                              <h3 class="mb-0"><%= link_to(event.name, event_path(event), class: "event-link") %></h3>
                            </div>
                            <div class="d-flex flex-column justify-content-between">
                          <div class="card-chip-description mb-4">
                            <p class="color-secondary"><i class="fas fa-calendar-times mr-3"></i>   <%= event.starts_at_formatted%> to <%= event.ends_at_time %></p>
                            <p id="host-icons"><i class="fas fa-user-friends mr-3"></i><i class="fas fa-caret-right"></i> <strong><%= link_to(event.user.username, user_path(event.user), class: "user-link") %></strong></p>
                          </div>
                          <div class="row justify-content-around">
                          <div class="card-chip-spots d-flex flex-column">
                            <p class="p-2 mt-1 <%=if request.status == "pending"
                            "pending-button"
                            elsif request.status == "confirmed"
                            "confirmed-button"
                            elsif request.status =="declined"
                            "declined-button color white"
                            else "cancelled-button"
                            end %>"><%= request.status %></p>
                          </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
                <% end %>
                <% else %>
                <p>You have no upcoming events</p>
                <% end %>
              </div>
            </div>
          </div>
          <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <div class="past-events">
              <section class="section">
                <div class="container py-1">
                  <div class="">
                    <div class="row h-100 justify-content-center">
                      <% if @past_requests.length > 0 %>
                      <% @past_requests.each do |request| %>
                      <% event = request.event %>
                      <div class="col-lg-4 col-sm-12 p-0 m-4">
                        <div class="card-chip">
                          <div class="event-content d-flex flex-column">
                          <div class="card-chip-image mb-3" style="background-image: linear-gradient(rgba(0,0,0,0.0), rgba(0,0,0,0.2)),url(<%= cl_image_path event.photo.key %>)">
                          </div>
                              <div class="event-content p-3">
                                <div class="card-chip-title text-center">
                                  <h3 class="mb-0"><%= link_to(event.name, event_path(event), class: "event-link") %></h3>
                                </div>
                                  <div class="d-flex flex-column justify-content-between">
                                  <div class="card-chip-description">
                                    <p class="color-secondary"><i class="fas fa-calendar-times mr-3"></i>   <%= event.starts_at_formatted%> to <%= event.ends_at_time %></p>
                                    <p id="host-icons"><i class="fas fa-user-friends mr-3"></i><i class="fas fa-caret-right"></i> <strong><%= link_to(event.user.username, user_path(event.user), class: "user-link") %></strong></p>
                                    <div class="row justify-content-around">
                                    <%= link_to "Review the host", new_user_review_path(event.user), class: "button-chip-main" %>
                                  </div>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <% end %>
                      <% else %>
                        <p>You have no past events</p>
                        <% end %>
                      </div>
                    </div>
                  </div>
                </section>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>

    <% else %>
    <section class="section">
      <div class= "container py-4">
        <h1>Events</h1>
        <hr>
        <div class="">
          <div class="row justify-content-center">
            <% if @events %>
            <% @events.each do |event| %>
            <div class="card-chip m-4 col-xl-3 col-lg-3 p-0 text-center">
              <div class="event-content p-3">
                <h2><%= link_to(event.name, event_path(event), class: "event-link") %></h2>
                <p>(FROM <%= event.starts_at_formatted%> TO <%= event.ends_at_formatted%>)</p>
                <% event.requests.each do |request| %>
                <p>Request sent by: <%= link_to(request.user.full_name, user_path(request.user), class: "user-link") %> <%= link_to(request.status, edit_event_request_path(request.event_id, request.id))%></p>
                <% end %>
              </div>
            </div>
            <% end %>
            <% end %>
          </div>
        </div>
      </div>
    </section>
    <% end %>
  </div>

app/views/requests/_form.html.erb
<%= simple_form_for [@event, @request] do |f| %>
  <%= f.input :message %>
  <%= f.submit 'Send', class: "button-chip-main"%>
<% end %>

app/views/requests/confirmation.html.erb
<div class="container">
  <div class="banner-confirm d-flex justify-content-center">
    <%=cl_image_tag('https://res.cloudinary.com/dqlvehu5z/image/upload/v1583936985/FgC6EQ9EvJ7gtqEWL5eGVkUC.jpg')%>
  </div>
  <div class="container">
      <h1 class="d-flex justify-content-center confirm-text">Your Application Has Been Sent!</h1>
      <p class="d-flex justify-content-center confirm-text">You will receive a confirmation soon!</p>
      <div class="button-row d-flex justify-content-center confirm-text">
          <%= link_to 'My Events', dashboard_path, class: "button-chip-main" %>
      </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://res.cloudinary.com/dqlvehu5z/image/upload/v1583424588/CHIP-IN/Charities%20pics/world_cjvsmh.png" %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if current_user %>
        <% if current_user.notifications > 0 %>
          <li >
            <%= link_to dashboard_path do %>
              <div>
                <button type="button" class="btn brn-primary">
                Notification <span class="badge badge-danger"><%= current_user.notifications %></span>
              </button>
                <!-- <i class="far fa-envelope blink no-bullet-points"></i> -->
              </div>
            <% end %>
          </li>
        <% end  %>
      <% end %>

      <% if current_user %>
        <li class="nav-item">
          <div class="hover-underline">
            <%= link_to "HOME", root_path, class: "nav-link hover hover-1" %>
          </div>
        </li>
        <li class="nav-item">
          <div class="hover-underline">
            <%= link_to "ALL EVENTS", events_path, class: "nav-link hover hover-1" %> <!-- root_path is a placeholder for now -->
          </div>
        </li>
        <li class="nav-item">
          <div class="hover-underline">
            <%= link_to "MY EVENTS", dashboard_path, class: "nav-link hover hover-1" %>
          </div>
        </li>
        <li class="nav-item dropdown">
        <% if current_user %>
            <%= if current_user.photo.attached?
              cl_image_tag current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false
            else
             image_tag "https://res.cloudinary.com/dqlvehu5z/image/upload/v1583424588/CHIP-IN/Charities%20pics/world_cjvsmh.png", style: 'width:35px'
          end
            %>
        <% end %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <% if current_user %>
            <%= link_to "Profile", user_path(current_user.id), class: "dropdown-item" %>
          <% end %>
          <% if current_user.role == "Charity" %>
            <%= link_to "Add event", new_event_path, class: "dropdown-item" %>
          <% end %>
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </li>
      <% else %>
        <li class="nav-item">
          <div class="hover-underline">
            <%= link_to "Log in", user_session_path, class: "nav-link hover hover-1" %>
          </div>
        </li>
      <% end %>
    </ul>
  </div>
</div>